// Auto-generated driver registry — forces all driver TUs into the final link
// so that their static self-registration initializers run at startup.

extern void wmbus_anchor_driver_abbb23(void);
extern void wmbus_anchor_driver_aerius(void);
extern void wmbus_anchor_driver_amiplus(void);
extern void wmbus_anchor_driver_apator08(void);
extern void wmbus_anchor_driver_apator162(void);
extern void wmbus_anchor_driver_apator172(void);
extern void wmbus_anchor_driver_apatoreitn(void);
extern void wmbus_anchor_driver_apatorna1(void);
extern void wmbus_anchor_driver_auto(void);
extern void wmbus_anchor_driver_aventieshca(void);
extern void wmbus_anchor_driver_aventieswm(void);
extern void wmbus_anchor_driver_bfw240radio(void);
extern void wmbus_anchor_driver_c5isf(void);
extern void wmbus_anchor_driver_cma12w(void);
extern void wmbus_anchor_driver_compact5(void);
extern void wmbus_anchor_driver_dme_07(void);
extern void wmbus_anchor_driver_ebzwmbe(void);
extern void wmbus_anchor_driver_ehzp(void);
extern void wmbus_anchor_driver_ei6500(void);
extern void wmbus_anchor_driver_elf(void);
extern void wmbus_anchor_driver_em24(void);
extern void wmbus_anchor_driver_emerlin868(void);
extern void wmbus_anchor_driver_enercal(void);
extern void wmbus_anchor_driver_engelmann_faw(void);
extern void wmbus_anchor_driver_esyswm(void);
extern void wmbus_anchor_driver_eurisii(void);
extern void wmbus_anchor_driver_ev200(void);
extern void wmbus_anchor_driver_evo868(void);
extern void wmbus_anchor_driver_fhkvdataiii(void);
extern void wmbus_anchor_driver_fhkvdataiv(void);
extern void wmbus_anchor_driver_flowiq2200(void);
extern void wmbus_anchor_driver_gransystems(void);
extern void wmbus_anchor_driver_gwfwater(void);
extern void wmbus_anchor_driver_hcae2(void);
extern void wmbus_anchor_driver_hydrocalm3(void);
extern void wmbus_anchor_driver_hydroclima(void);
extern void wmbus_anchor_driver_hydrodigit(void);
extern void wmbus_anchor_driver_hydrus(void);
extern void wmbus_anchor_driver_iem3000(void);
extern void wmbus_anchor_driver_iperl(void);
extern void wmbus_anchor_driver_itron(void);
extern void wmbus_anchor_driver_iwmtx5(void);
extern void wmbus_anchor_driver_izar(void);
extern void wmbus_anchor_driver_kamheat(void);
extern void wmbus_anchor_driver_kampress(void);
extern void wmbus_anchor_driver_lansendw(void);
extern void wmbus_anchor_driver_lansenpu(void);
extern void wmbus_anchor_driver_lansenrp(void);
extern void wmbus_anchor_driver_lansensm(void);
extern void wmbus_anchor_driver_lansenth(void);
extern void wmbus_anchor_driver_lse_07_17(void);
extern void wmbus_anchor_driver_lse_08(void);
extern void wmbus_anchor_driver_microclima(void);
extern void wmbus_anchor_driver_minomess(void);
extern void wmbus_anchor_driver_mkradio3(void);
extern void wmbus_anchor_driver_mkradio3a(void);
extern void wmbus_anchor_driver_mkradio4(void);
extern void wmbus_anchor_driver_mkradio4a(void);
extern void wmbus_anchor_driver_multical21(void);
extern void wmbus_anchor_driver_munia(void);
extern void wmbus_anchor_driver_nemo(void);
extern void wmbus_anchor_driver_omnipower(void);
extern void wmbus_anchor_driver_piigth(void);
extern void wmbus_anchor_driver_pollucomf(void);
extern void wmbus_anchor_driver_q400(void);
extern void wmbus_anchor_driver_qcaloric(void);
extern void wmbus_anchor_driver_qheat(void);
extern void wmbus_anchor_driver_qheat_55_us(void);
extern void wmbus_anchor_driver_qsmoke(void);
extern void wmbus_anchor_driver_qualcosonic(void);
extern void wmbus_anchor_driver_qwater(void);
extern void wmbus_anchor_driver_rfmamb(void);
extern void wmbus_anchor_driver_rfmtx1(void);
extern void wmbus_anchor_driver_sensostar(void);
extern void wmbus_anchor_driver_sharky(void);
extern void wmbus_anchor_driver_sharky774(void);
extern void wmbus_anchor_driver_sontex868(void);
extern void wmbus_anchor_driver_supercom587(void);
extern void wmbus_anchor_driver_topaseskr(void);
extern void wmbus_anchor_driver_tsd2(void);
extern void wmbus_anchor_driver_ultraheat(void);
extern void wmbus_anchor_driver_ultrimis(void);
extern void wmbus_anchor_driver_unismart(void);
extern void wmbus_anchor_driver_unknown(void);
extern void wmbus_anchor_driver_vario411(void);
extern void wmbus_anchor_driver_vario451(void);
extern void wmbus_anchor_driver_vario451mid(void);
extern void wmbus_anchor_driver_waterstarm(void);
extern void wmbus_anchor_driver_watertech(void);
extern void wmbus_anchor_driver_weh_07(void);
extern void wmbus_anchor_driver_wme5(void);

void wmbus_ensure_all_drivers(void) {
    wmbus_anchor_driver_abbb23();
    wmbus_anchor_driver_aerius();
    wmbus_anchor_driver_amiplus();
    wmbus_anchor_driver_apator08();
    wmbus_anchor_driver_apator162();
    wmbus_anchor_driver_apator172();
    wmbus_anchor_driver_apatoreitn();
    wmbus_anchor_driver_apatorna1();
    wmbus_anchor_driver_auto();
    wmbus_anchor_driver_aventieshca();
    wmbus_anchor_driver_aventieswm();
    wmbus_anchor_driver_bfw240radio();
    wmbus_anchor_driver_c5isf();
    wmbus_anchor_driver_cma12w();
    wmbus_anchor_driver_compact5();
    wmbus_anchor_driver_dme_07();
    wmbus_anchor_driver_ebzwmbe();
    wmbus_anchor_driver_ehzp();
    wmbus_anchor_driver_ei6500();
    wmbus_anchor_driver_elf();
    wmbus_anchor_driver_em24();
    wmbus_anchor_driver_emerlin868();
    wmbus_anchor_driver_enercal();
    wmbus_anchor_driver_engelmann_faw();
    wmbus_anchor_driver_esyswm();
    wmbus_anchor_driver_eurisii();
    wmbus_anchor_driver_ev200();
    wmbus_anchor_driver_evo868();
    wmbus_anchor_driver_fhkvdataiii();
    wmbus_anchor_driver_fhkvdataiv();
    wmbus_anchor_driver_flowiq2200();
    wmbus_anchor_driver_gransystems();
    wmbus_anchor_driver_gwfwater();
    wmbus_anchor_driver_hcae2();
    wmbus_anchor_driver_hydrocalm3();
    wmbus_anchor_driver_hydroclima();
    wmbus_anchor_driver_hydrodigit();
    wmbus_anchor_driver_hydrus();
    wmbus_anchor_driver_iem3000();
    wmbus_anchor_driver_iperl();
    wmbus_anchor_driver_itron();
    wmbus_anchor_driver_iwmtx5();
    wmbus_anchor_driver_izar();
    wmbus_anchor_driver_kamheat();
    wmbus_anchor_driver_kampress();
    wmbus_anchor_driver_lansendw();
    wmbus_anchor_driver_lansenpu();
    wmbus_anchor_driver_lansenrp();
    wmbus_anchor_driver_lansensm();
    wmbus_anchor_driver_lansenth();
    wmbus_anchor_driver_lse_07_17();
    wmbus_anchor_driver_lse_08();
    wmbus_anchor_driver_microclima();
    wmbus_anchor_driver_minomess();
    wmbus_anchor_driver_mkradio3();
    wmbus_anchor_driver_mkradio3a();
    wmbus_anchor_driver_mkradio4();
    wmbus_anchor_driver_mkradio4a();
    wmbus_anchor_driver_multical21();
    wmbus_anchor_driver_munia();
    wmbus_anchor_driver_nemo();
    wmbus_anchor_driver_omnipower();
    wmbus_anchor_driver_piigth();
    wmbus_anchor_driver_pollucomf();
    wmbus_anchor_driver_q400();
    wmbus_anchor_driver_qcaloric();
    wmbus_anchor_driver_qheat();
    wmbus_anchor_driver_qheat_55_us();
    wmbus_anchor_driver_qsmoke();
    wmbus_anchor_driver_qualcosonic();
    wmbus_anchor_driver_qwater();
    wmbus_anchor_driver_rfmamb();
    wmbus_anchor_driver_rfmtx1();
    wmbus_anchor_driver_sensostar();
    wmbus_anchor_driver_sharky();
    wmbus_anchor_driver_sharky774();
    wmbus_anchor_driver_sontex868();
    wmbus_anchor_driver_supercom587();
    wmbus_anchor_driver_topaseskr();
    wmbus_anchor_driver_tsd2();
    wmbus_anchor_driver_ultraheat();
    wmbus_anchor_driver_ultrimis();
    wmbus_anchor_driver_unismart();
    wmbus_anchor_driver_unknown();
    wmbus_anchor_driver_vario411();
    wmbus_anchor_driver_vario451();
    wmbus_anchor_driver_vario451mid();
    wmbus_anchor_driver_waterstarm();
    wmbus_anchor_driver_watertech();
    wmbus_anchor_driver_weh_07();
    wmbus_anchor_driver_wme5();
}
