substitutions:
  name: watermeter-peter
  friendly_name: watermeter_peter
    
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  devices:
    - id: lorenz_23120547_device
      name: "watermeter peter 1"

esp32:
  board: esp32dev
  framework:
    type: esp-idf


logger:
  level: DEBUG  # Debug level to show frame hex dumps
  tx_buffer_size: 2048  # Increased buffer to prevent log truncation
  baud_rate: 115200 # is default
  logs:
    component: INFO     # Reduce noise from other components
    esp32: INFO # Reduce noise from other components
    spi: INFO # Reduce noise from other components
    app: INFO # Reduce noise from other components
    wifi: ERROR         # Disable WiFi scan logs
    wmbus_radio: DEBUG  # Show frame hex dumps
    cc1101: DEBUG       # Show CC1101 details

api:
  encryption:
    key: !secret api_watermeter_peter

ota:
  - platform: esphome
    password:  !secret ota_password_peter

wifi:
  ssid: !secret wifi_ssid
  password:  !secret wifi_password
  ap:
    ssid: "${name} Fallback"
    password: !secret "watermeter"

captive_portal:

time:
  - platform: homeassistant

button:
  - platform: restart
    id: "restart_${friendly_name}"
    name: "restart_${friendly_name}"

external_components:
  - source: github://enr0c/esphome-components@toMain
    components: [ wmbus_radio, wmbus_meter, wmbus_common ]
    refresh: 0min

# Your wiring: 
# VCC = red       -> 3.3V
# GND = orange    -> GND
# MOSI = yellow   -> GPIO23 (standard VSPI)
# S/CLK = green   -> GPIO18 (standard VSPI)
# MISO = blue     -> GPIO19 (standard VSPI)
# GDO2 = grey     -> GPIO27
# GDO0 = purple   -> GPIO26
# CSN = white     -> GPIO25

spi: 
  clk_pin:  GPIO18   # green
  mosi_pin: GPIO23  # yellow
  miso_pin: GPIO19  # blue

wmbus_radio:
  id: radio
  radio_type: CC1101
  cs_pin: GPIO25  # white
  gdo2_pin:
    number: GPIO27  # grey
    mode: INPUT_PULLDOWN
  gdo0_pin: GPIO26  # puprple
  frequency: 868.95
  on_frame:
    - then:
        - logger.log:
            level: DEBUG
            format: "RSSI: %ddBm T: %s (%d) %s"
            args: [ frame->rssi(), frame->as_hex().c_str(), frame->data().size(), toString(frame->link_mode()) ]

# wM-Bus common configuration
wmbus_common:
  drivers: all

wmbus_meter:
  - id: lorenz_23120547
    radio_id: radio
    meter_id: 0x23120547
    type: waterstarm
    key: !secret lorenz_23120547
    on_telegram:
          then:
            - logger.log:
                level: INFO
                format: "wmbus %s: %s"
                args:
                  - meter.get_id().c_str()
                  - meter.as_json(true).c_str()
sensor:
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "total"
    field: total_m3
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    device_class: water
    state_class: total_increasing
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "RSSI"
    field: rssi_dbm
    unit_of_measurement: "dBm"
    entity_category: diagnostic
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "Battery"
    field: battery_v
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_class: voltage
    entity_category: diagnostic
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "set date raw"  
    id: waschkeller_set_date_raw
    field: set_date
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "meter_datetime"
    id: waschkeller_meter_datetime
    field: meter_datetime    
text_sensor:
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "timestamp"
    field: timestamp_zulu
    device_class: timestamp
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "status"
    field: status
  - platform: wmbus_meter
    parent_id: lorenz_23120547
    device_id: lorenz_23120547_device
    name: "current status"
    field: current_status